# Generated by Django 2.1.5 on 2019-01-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjasAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency_rates',
            name='currency_id',
        ),
        migrations.AddField(
            model_name='currency_rates',
            name='currency',
            field=models.IntegerField(choices=[(1, 'PLN'), (2, 'EUR'), (3, 'USD'), (4, 'GBP')], default=1),
        ),
    ]
