# Generated by Django 2.1.5 on 2019-01-23 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninjasAPI', '0002_auto_20190123_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='sales_order_number',
        ),
    ]
